name: rclexample
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/rcldart/rclexample

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.3
  path: ^1.8.0

  rcldart:
    path: ../rcldart

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
